// <auto-generated />
using BlogHeaven.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogHeaven.Migrations
{
    [DbContext(typeof(BlogHeavenContext))]
    [Migration("20240311094046_BlogHeavenInitialMigration")]
    partial class BlogHeavenInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("BlogHeaven.Entities.Blog", b =>
                {
                    b.Property<int>("BloggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloggerDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BloggerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("BloggerId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("BlogHeaven.Entities.BlogsByBlogger", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlogDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BloggerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlogId");

                    b.HasIndex("BloggerId");

                    b.ToTable("BlogsByBlogger");
                });

            modelBuilder.Entity("BlogHeaven.Entities.BlogsByBlogger", b =>
                {
                    b.HasOne("BlogHeaven.Entities.Blog", "Blog")
                        .WithMany("BlogsByBlogger")
                        .HasForeignKey("BloggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("BlogHeaven.Entities.Blog", b =>
                {
                    b.Navigation("BlogsByBlogger");
                });
#pragma warning restore 612, 618
        }
    }
}
